language: node_js
node_js:
- 14
script:
- npm run lint
- npm run build
notifications:
  webhooks: https://open.feishu.cn/officialapp/notify/c4a1011904c5dc2efb332f1f80d817a88c8d829a2976d8c2c6f8bc4230c6e715

