version: 2.1

orbs:
  node: circleci/node@4.1
  aws-s3: circleci/aws-s3@2.0

jobs:
  lint-and-test:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run ESLint check
          command: npm run lint
      - run:
          name: Run unit test
          command: npm run test:unit
      - run:
          name: Run E2E test
          command: |
            apt-get install -yq libnss3 unzip openjdk-8-jre-headless xvfb libxi6 libgconf-2-4
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            curl -sS -o - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
            apt install -y ./google-chrome-stable_current_amd64.deb
            npm run test:e2e
  build-and-deploy-staging:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: build
          command: npm run build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: dist/
          to: s3://cpg-innovation-website-staging
  build-and-deploy-prod:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: build
          command: npm run build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: dist/
          to: s3://cpg-innovation-website          

workflows:
  default:
    jobs:
      - lint-and-test
      - build-and-deploy-staging:
          requires:
            - lint-and-test
          filters:
            branches:
              only: staging
      - build-and-deploy-prod:
          requires:
            - lint-and-test
          filters:
            branches:
              only: master

