version: 2.1

orbs:
  node: circleci/node@4.1
  aws-s3: circleci/aws-s3@2.0

jobs:
  lint-and-test:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test:unit
  build-and-deploy-staging:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: build
          command: npm run build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: dist/
          to: s3://cpg-innovation-website-staging
  build-and-deploy-prod:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: build
          command: npm run build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: dist/
          to: s3://cpg-innovation-website          

workflows:
  default:
    jobs:
      - lint-and-test
      - build-and-deploy-staging:
          requires:
            - lint-and-test
          filters:
            branches:
              only: staging
      - build-and-deploy-prod:
          requires:
            - lint-and-test
          filters:
            branches:
              only: master

