version: 2.1

orbs:
  node: circleci/node@4.1
  aws-s3: circleci/aws-s3@2.0

jobs:
  lint-and-test:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test:unit
  build-and-deploy-dev:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: build
          command: npm run build
      - aws-s3/sync:
          from: dist/
          to: s3://cpg-innovation-website/${CIRCLE_BRANCH}
  build-and-deploy-prod:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: build
          command: npm run build
      - aws-s3/sync:
          from: dist/
          to: s3://cpg-innovation-website

workflows:
  default:
    jobs:
      - lint-and-test
      - build-and-deploy-dev:
          requires:
            - lint-and-test
          filters:
            branches:
              ignore: master
      - build-and-deploy-prod:
          requires:
            - lint-and-test
          filters:
            branches:
              only: master

